BoletinAvances/apps/avances/urls.py
from django.conf.urls import patterns, url
from django.conf.urls.static import static
from django.conf import settings
from BoletinAvances.apps.avances.views import *
from django.contrib.auth.decorators import login_required


urlpatterns = patterns('BoletinAvances.apps.avances.views',
    #Diarios
    url(r'^Diariosver/?$', login_required(DiariosListView.as_view()), name='ver_diarios'),
    url(r'^Diariosenviar/?$', login_required(DiarioAddView.as_view()), name='enviar_diarios'),
    url(r'^Diariodetalle-(?P<slug>[-\w]+)/$', login_required(DiariosDetailView.as_view()), name='singlediarios_view'),
    url(r'^Diariosdel-(?P<slug>[-\w]+)/$', login_required(DiariosDeleteView.as_view()), name='diario_delete'),
    #Noticias
    url(r'^Noticiasver/?$', login_required(NoticiasListView.as_view()), name='ver_noticias'),
    url(r'^Noticiasenviar/?$', login_required(NoticiasAddView.as_view()), name='enviar_noticia'),
    url(r'^Noticiasdetalle-(?P<slug>[-\w]+)/$', login_required(NoticiasDetailView.as_view()), name='singlenoticias_view'),
    url(r'^Noticiasdel-(?P<slug>[-\w]+)/$', login_required(NoticiasDeleteView.as_view()), name='noticia_delete'),
    #Avances
    url(r'^Avancesver/?$', login_required(AvancesListView.as_view()), name='ver_avances'),
    url(r'^Avancesenviar/?$', login_required(AvancesAddView.as_view()), name='enviar_avance'),
    url(r'^Avancesdetalle-(?P<slug>[-\w]+)/$', login_required(AvancesDetailView.as_view()), name='singleavance_view'),
    url(r'^Avancesdel-(?P<slug>[-\w]+)/$', login_required(AvancesDeleteView.as_view()), name='avance_delete'),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BoletinAvances/apps/listas/urls.py
from django.conf.urls import patterns, url
from django.conf.urls.static import static
from django.conf import settings
from BoletinAvances.apps.listas.views import *
from django.contrib.auth.decorators import login_required


urlpatterns = patterns('BoletinAvances.apps.listas.views',
    url(r'^AddlistManual/?$', login_required(ListasManualAddView.as_view()), name='addlistas'),
    url(r'^AddlistasMasivo/?$', 'upload_data_list', name='AddlistasMasivo'),
    url(r'^listas/?$', login_required(ListasListView.as_view()), name='listas'),
    url(r'^listaview-(?P<slug>[-\w]+)/$', login_required(ListasDetailView.as_view()), name='singlelistas_view'),
    url(r'^listadel-(?P<slug>[-\w]+)/$', login_required(ListaDeleteView.as_view()), name='listas_delete'),
    url(r'^listaup-(?P<slug>[-\w]+)/$', login_required(ListasUpdate.as_view()), name='listas_update'),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BoletinAvances/apps/login/urls.py
from django.conf.urls import patterns, url
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required, permission_required
from BoletinAvances.apps.login.views import *
from django.conf import settings


urlpatterns = patterns('BoletinAvances.apps.login.views',
    url(r'^$', 'login_view', name='login_view'),
    url(r'^logout/', 'logout_view', name='logout_view'),
    url(r'^tablero/$','graph_view', name='graph_view'),
    url(r'^administracion/usuarios/$','usuarios_view', name='usuarios'),
    url(r'^administracion/anadirusuario/','register_view',name='anadirusuario'),
    url(r'^administracion/usuariosin-(?P<id>.*)/$','singleusuarios_view',name='singleusuarios_view'),
    url(r'^administracion/usuariodel-(?P<id>.*)/$','singleusuarios_delete',name='singleusuarios_delete'),
    url(r'^administracion/usuarioup-(?P<slug>[-\w]+)/$', login_required(UsuariosUpdate.as_view()), name='updateusuarios_view'),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BoletinAvances/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.views.generic import TemplateView

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^', include('BoletinAvances.apps.login.urls')),
    url(r'^administracion/', include('BoletinAvances.apps.listas.urls')),
    url(r'^administracion/', include('BoletinAvances.apps.contactos.urls')),
    url(r'^boletines/', include('BoletinAvances.apps.boletines.urls')),
    url(r'^avances/', include('BoletinAvances.apps.avances.urls')),
	url(r'^primerasplanas/', include('BoletinAvances.apps.primerasplanas.urls')),
    url(r'^resumen/', include('BoletinAvances.apps.resumen.urls')),
)

BoletinAvances/apps/avances/models.py
from django.db import models
from datetime import datetime
from BoletinAvances.apps.listas.models import Listas


TIPO_ENVIO = (
    ('Automatico', 'Automatico'),
    ('Programado', 'Programado'),
)


TAG = (
    ('0', '----'),
    ('REG', 'Regionales'),
    ('NAC', 'Nacionales'),
    ('INT', 'Internacionales'),
    ('ECO', 'Economia'),
    ('DEP', 'Deporte'),
    ('SUC', 'Sucesos'),
)


class Avances(models.Model):
   '''Clase para los avances'''
   fecha = models.DateField(default=datetime.now, blank=True)
   hora = models.TimeField(auto_now_add=True, blank=True)
   tipo_envio = models.CharField(max_length=20, choices=TIPO_ENVIO, default='0', verbose_name='Tipo de envio')
   status = models.CharField(max_length=110, verbose_name='Status', blank=True, null=True)
   listas = models.ManyToManyField(Listas)
   titulo_mensaje = models.CharField(max_length=1000, verbose_name='Titulo')
   cuerpo_mensaje = models.TextField(verbose_name='Cuerpo del mensaje')
   enviadopor = models.CharField(max_length=50, verbose_name='Enviado por:')

   class Meta:
      verbose_name_plural = "Agregar avances"
      ordering = ('fecha', 'tipo_envio', 'titulo_mensaje', 'status', 'enviadopor')

   def __unicode__(self):
      ''':return: Representacion en cadena de la clase avances'''
      boletin = "Estatus: %s - Titulo: %s - Tipo de envio: %s" % (self.status, self.titulo_mensaje, self.tipo_envio)
      return boletin


class Diarios(models.Model):
   '''Clase para los diarios'''
   pais = models.CharField(max_length=110, verbose_name='Pais', blank=True, null=True)
   estado = models.CharField(max_length=110, verbose_name='Estado', blank=True, null=True)
   nombre_diario = models.CharField(max_length=110, verbose_name='Diario', blank=True, null=True)

   class Meta:
      verbose_name_plural = "Agregar diario"
      ordering = ('nombre_diario',)

   def __unicode__(self):
      ''':return: Representacion en cadena de la clase diarios'''
      diario = "Diario: %s" % (self.nombre_diario,)
      return diario


class Noticias(models.Model):
    '''Clase para noticias'''
    #Campos necesarios
    avances = models.ForeignKey(Avances, verbose_name='Avances', blank=True, null=True)
    fecha = models.DateField(default=datetime.now, blank=True)
    hora = models.TimeField(auto_now_add=True, blank=True, null=True)
    tag = models.CharField(max_length=30, verbose_name='Etiqueta', choices=TAG, default='')
    status = models.CharField(max_length=110, verbose_name='Status', blank=True, null=True)
    enviadopor = models.CharField(max_length=50, verbose_name='Enviado por:')
    titulo_noticia = models.CharField(max_length=500, verbose_name='Titulo')
    antetitulo_noticia = models.CharField(max_length=500, verbose_name='Antetitulo', blank=True)
    enviadopor = models.CharField(max_length=50, verbose_name='Enviado por:')
    noticia = models.TextField(verbose_name='Extracto de la noticia')

    class Meta:
        verbose_name_plural = "Agregar noticias para avances"
        ordering = ('status',)

    def __unicode__(self):
        ''':return: Representacion en cadena de la clase noticias'''
        noticia = "ID: %s - Titulo de noticia: %s " % (self.id, self.titulo_noticia)
        return noticia


class EnlaceDiarios(models.Model):
    ''' Clase para vincular enlaces con Diarios '''
    diario = models.ForeignKey(Diarios)
    noticia = models.ForeignKey(Noticias)
    url = models.URLField(verbose_name='Enlace de noticia')

    class Meta:
        verbose_name_plural = "Enlace de Noticias"
        ordering = ('diario', 'noticia', 'url')

    def __unicode__(self):
        url = "Diario: %s - URL: %s" % (self.diario, self.url)
        return url

BoletinAvances/apps/columnadeopinion/models.py
from django.db import models

# Create your models here.

BoletinAvances/apps/avances/views.py
import hashlib
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, FormView, DetailView, DeleteView
from django.contrib import messages

from BoletinAvances.apps.listas.models import Listas
from BoletinAvances.apps.listas.forms import ListasForm
from BoletinAvances.apps.contactos.models import Contactos
from BoletinAvances.apps.contactos.forms import ContactosForm
from BoletinAvances.apps.avances.models import Avances, Diarios, Noticias, EnlaceDiarios
from BoletinAvances.apps.avances.forms import AvancesForm, DiariosForm, NoticiasForm, NoticiasFormSet, EnlaceDiariosFormSet

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import BadHeaderError, EmailMessage
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext, Context
from django.core.mail import EmailMessage, send_mail, EmailMultiAlternatives
from django.template.loader import get_template
import os
from django.conf import settings
from django.shortcuts import get_object_or_404, render


#LISTAR DIARIOS
class DiariosListView(ListView):
    model = Diarios
    queryset = Diarios.objects.order_by('id')
    context_object_name = "Diarios"
    template_name = "Diarios/listaDiarios.html"

#CREAR DIARIOS
class DiarioAddView(FormView):
    form_class = DiariosForm
    success_url = reverse_lazy('ver_diarios')
    template_name = "Diarios/enviarDiarios.html"

    def form_valid(self, form):
        form.save(commit=True)
        messages.success(self.request, 'Diario cargado!', fail_silently=True)
        return super(DiarioAddView, self).form_valid(form)

#INDIVIDUAL DIARIOS
class DiariosDetailView(DetailView):
    model = Diarios
    slug_field = 'id'
    template_name="Diarios/singleDiarios.html"

#ELIMINAR DIARIOS
class DiariosDeleteView(DeleteView):
    model = Diarios
    slug_field = 'id'
    template_name='Diarios/diarios_confirm_delete.html'
    success_url = '/avances/Diariosver'

#LISTAS NOTICIAS
class NoticiasListView(ListView):
    model = Noticias
    queryset = Noticias.objects.order_by('id')
    context_object_name = "Noticias"
    template_name = "Noticias/listaNoticias.html"

#CREAR NOTICIAS
class NoticiasAddView(FormView):
    model = Noticias
    form_class = NoticiasForm
    formset = EnlaceDiariosFormSet()
    success_url = reverse_lazy('ver_noticias')
    template_name = "Noticias/enviarNoticia.html"

    def get(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        formset = EnlaceDiariosFormSet(instance=Noticias())
        return self.render_to_response(
            self.get_context_data(form=form,
                                  formset=formset))

    def post(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        noticias = form.save()
        formset = EnlaceDiariosFormSet(request.POST, request.FILES, instance=noticias)
        if (form.is_valid() and formset.is_valid()):
            return self.form_valid(form, formset)
        else:
            return self.form_invalid(form, formset)

    def form_valid(self, form, formset):
        form.instance.status = 'Borrador'
        self.object = form.save()
        formset.instance = self.object
        formset.save()
        return super(NoticiasAddView, self).form_valid(form)

    def form_invalid(self, form, formset):
        """
        Called if a form is invalid. Re-renders the context data with the
        data-filled forms and errors.
        """
        return self.render_to_response(
            self.get_context_data(form=form,
                                  formset=formset))


#INDIVIDUAL NOTICIAS
class NoticiasDetailView(DetailView):
    model = Noticias
    slug_field = 'id'
    template_name="Noticias/singlenoticias.html"

    def get_context_data(self, **kwargs):
        context = super(NoticiasDetailView, self).get_context_data(**kwargs)
        noticia = self.object
        context["enlaces"] = EnlaceDiarios.objects.filter(noticia=noticia)
        return context


#ELIMINAR NOTICIAS
class NoticiasDeleteView(DeleteView):
    model = Noticias
    slug_field = 'id'
    success_url = '/avances/Noticiasver'

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

#LISTAS AVANCES
class AvancesListView(ListView):
    model = Avances
    queryset = Avances.objects.order_by('id')
    context_object_name = "Avances"
    template_name = "avances/listaAvances.html"


#CREAR AVANCES
class AvancesAddView(FormView):
    model = Avances
    form_class = AvancesForm
    success_url = reverse_lazy('ver_avances')
    template_name = "avances/enviarAvance.html"


    def get_context_data(self, **kwargs):
        context = super(AvancesAddView, self).get_context_data(**kwargs)
        context["Noticias"] = Noticias.objects.all().filter(status__startswith='Borrador')
        return context


    def get(self, request, *args, **kwargs):
        """
        Handles GET requests and instantiates blank versions of the form
        and its inline formsets.
        """
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        return self.render_to_response(
            self.get_context_data(form=form))


    def post(self, request, *args, **kwargs):
        """
        Handles POST requests, instantiating a form instance and its inline
        formsets with the passed POST variables and then checking them for
        validity.
        """
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        avances = form.save()
        if (form.is_valid()):
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form, **kwargs):
        """
        Called if all forms are valid. Creates a Avances instance along with
        associated Noticias and then redirects to a success page.
        """
        form.instance.status = 'Borrador'
        self.object = form.save()
        avance = self.object.id

        ### MODIFICAR SENDER
        sender = 'guadarramaangel@gmail.com'
        titulo_mensaje = self.object.titulo_mensaje
        cuerpo_mensaje = self.object.cuerpo_mensaje
        recipients = self.object.listas.all()
        recipients_final = []
        for lista in recipients:
            for contacto in Contactos.objects.filter(listas=lista):
                recipients_final.append(contacto.correo)
        #Pasar datos a plantilla
        context = self.get_context_data(**kwargs)
        noticias =  context['Noticias']
        indices = self.request.POST['feeds']
        indices = indices.split(',')
        container = []
        for a in noticias:
            for i in indices:
                if i == str(a.pk):
                    feed = {}
                    feed['id'] = a.pk
                    feed['fecha'] = a.fecha
                    feed['hora'] = a.hora
                    feed['tag'] = a.tag
                    feed['antetitulo_noticia'] = a.antetitulo_noticia
                    feed['titulo'] = a.titulo_noticia
                    feed['noticia'] = a.noticia
                    feed['enlaces'] = EnlaceDiarios.objects.filter(noticia = a.pk)
                    #Cambiar el status:
                    b = Noticias.objects.get(pk = a.pk)
                    b.status = "Enviado"
                    b.save()
                    #Llenando lista con noticias
                    container.append(feed)
        #Render context a plantilla
        htmly = get_template('avances/AvancesEmail.html')
        d = {'titulo_mensaje': titulo_mensaje,
             'cuerpo_mensaje': cuerpo_mensaje,
             'data_noticias': container}
        html_content = htmly.render(d)
        #Enviar correo
        email = EmailMessage(titulo_mensaje, html_content, sender, [], recipients_final)
        email.content_subtype = 'html'
        email.send()
        #Cambiar estatus de boletin
        c = Avances.objects.get(id=avance)
        c.status = "Enviado"
        c.save()
        return HttpResponseRedirect("/avances/Avancesver")


    def form_invalid(self, form, formset):
        """
        Called if a form is invalid. Re-renders the context data with the
        data-filled forms and errors.
        """
        return self.render_to_response(
            self.get_context_data(form=form))


#INDIVIDUAL AVANCES
class AvancesDetailView(DetailView):
    model = Avances
    slug_field = 'id'
    template_name="avances/singleavance.html"

    def get_context_data(self, **kwargs):
        context = super(AvancesDetailView, self).get_context_data(**kwargs)
        avance = self.object
        context["noticias"] = Noticias.objects.filter(avances=avance)
        return context


#ELIMINAR AVANCES
class AvancesDeleteView(DeleteView):
    model = Avances
    slug_field = 'id'
    success_url = '/avances/Avancesver'

    def get_context_data(self, **kwargs):
        context = super(AvancesDeleteView, self).get_context_data(**kwargs)
        avance = self.object
        context["noticias"] = Noticias.objects.filter(avances=avance)
        return context

BoletinAvances/apps/columnadeopinion/views.py
from django.shortcuts import render

# Create your views here.

BoletinAvances/templates/boletines/boletines_confirm_delete.html
{% extends 'menu/menu.html' %}
{% block content-wrapper %}
{% load static %}

        <section class="content-header">
          <h1>
            Boletines
            <small>Eliminar boletín</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Inicio</a></li>
            <li><a href="#">Boletines</a></li>
            <li class="active">Eliminar boletín</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            <!-- left column -->
            <div class="col-md-12">
              <!-- general form elements -->
              <div class="box box-primary">
                <div class="box-header">
                  <h3 class="box-title">¿Seguro quiere eliminar el boletín?</h3>
                </div><!-- /.box-header -->
                  <!-- form start -->
                  <form id="multiselectForm" action="" method="post" enctype="multipart/form-data">{% csrf_token %}
																	  
                    <div class="large-12 columns">
                        <div class="table-responsive" id="file_container" style="display:block">
                    
                            <table class="table">
                                <tr>
                                    <th style="width: 20%">Tipo de envio</th>
                                    <th style="width: 20%">Fecha</th>
                                    <th style="width: 20%">Hora</th>
                                    <th>Lista(s) disponible(s):</th>
                                </tr>
                                <tr>
                                    <td>
                                        <input type="text" value="{{ object.tipo_envio }}" readonly name="tipo_envio">
                                    </td>
                                    <td>
                                        <input type="text" value="{{ object.fecha|date:'d/m/Y' }}" readonly name="fecha">
                                    </td>
                                    <td>
                                        <input type="text" value="{{ object.hora|date:'h:i A' }}" readonly name="hora">
                                    </td>
                                    <td>
                                        <input type="text" readonly value="{% for objs in object.listas.all %}{{ objs }} {% endfor %}" name="listas">
                                    </td>
                              </tr>  
                            </table>
            
                            <label for="titulomensaje"><h5>Titulo del mensaje:</h5></label>
                            <input type="text" style="width: 100%" value="{{ object.titulo_mensaje }}" readonly name="titulo_mensaje">
                            <label for="cuerpomensaje"><h5>Cuerpo del mensaje:</h5></label>
                            <textarea style='width: 100%;' readonly class="form-control" maxlength="1000" rows="4" value="{{ object.cuerpo_mensaje }}" name="cuerpo_mensaje">{{ object.cuerpo_mensaje }}</textarea>
                  
                        </div>
                    </div>
                    
                    <div class="large-12 columns">
                        <div class="table-responsive" id="file_container" style="display:block">
                    
                            <table class="table">
                                <tr>
                                    <th style="width: 20%">Enviado por</th>
                                    <th style="width: 20%">Estatus</th>
                                </tr>
                                <tr>
                                    <td>
                                        <input type="text" value="{{ object.enviadopor }}" readonly name="enviadopor">
                                    </td>
                                    <td>
                                        <input type="text" value="{{ object.status }}" readonly name="status">
                                    </td>
                              </tr>  
                            </table>
                        </div>
                    </div>
                    
                    <hr>
                    <div class="box-header" data-original-title>
                        <h2 class="box-title">Archivos adjuntados:</h2>
                    </div>
                    <div>
                        <table class="table table-bordered">
                            <tr>
                                <th style="background-color: #222D32; color: white; width: 3%;">Ubicación del archivo<span class="fa fa-cloud"></span></th>
                                <th style="background-color: #222D32; color: white; width: 1%;">Tamaño del archivo </th>
                                <th style="background-color: #222D32; color: white; width: 1%;">Acciones <span class="fa fa-inbox"></span></th>
                            </tr>
                            {% for file in archivos %}
                            <tr>  
                                <td>
                                    {{ file.documento }}
                                </td>
                                <td> 
                                    {{ file.documento.size|filesizeformat }}
                                </td>
                                <td>
                                    || <a href="{% get_media_prefix %}{{ file.documento }}" target="_blank"> Abrir <span class="fa fa-eye"></span></a> |
                                    | <a href="{% get_media_prefix %}{{ file.documento }}" download> Descargar <span class="fa fa-download"></span></a> ||
                                </td>
                            </tr>
                            {% endfor %}
                        </table>
                    </div>

                    <div class="box-footer">
                      <button type="submit" class="btn btn-block btn-primary btn-lg">Eliminar Boletín</button>
                    </div>

                  </form>
      
                </div><!-- /.box -->
              </div><!--/.col (right) -->
            </div>   <!-- /.row -->
          </section><!-- /.content -->


{% endblock %}

BoletinAvances/templates/boletines/enviarBoletin.html
{% extends 'menu/menu.html' %}
{% block content-wrapper %}
{% load static %}

    <!-- Formsets -->
    <script src="{{ STATIC_URL }}js/jquery.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}js/jquery.formset.js" type="text/javascript"></script>


	<style>
	  #bottom-right
		{
		  float: right;
		  margin-top:-1.6%;
		}

	</style>

        <section class="content-header">
          <h1>
            Boletines
            <small>Enviar Boletin</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Inicio</a></li>
            <li><a href="#">Boletines</a></li>
            <li class="active">Enviar Boletin</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="col-xs-12">
              <div class="box">
                <div class="box-header">
                  <h3 class="box-title">Enviar Boletin</h3>
                </div><!-- /.box-header -->
                <div class="box-body">

					<form id="multiselectForm" action="{% url 'enviar_boletin' %}" method="post" enctype="multipart/form-data">

					  {% csrf_token %}

						<div class="large-12 columns">
							<div class="table-responsive" id="form_data">

								<table class="table">
								  <tr>
									<th style="width: 20%">Tipo de envio</th>
									<th style="width: 20%">Fecha</th>
									<th style="width: 20%">Hora</th>
									<th>Listas disponibles</th>
								  </tr>
								  <tr>
									<td>
									  <select style="width: 70%" class="form-control" id="tipo_envio" name="tipo_envio" value="{{ tipo_envio }}" required>
										  {% for x,y in form.fields.tipo_envio.choices %}
											  <option value="{{ x }}"{% if form.fields.tipo_envio.value == x %} {% endif %}>{{ y }}</option>
										  {% endfor %}
									  </select>
									</td>
									<td>
									  <div style="width: 80%">
										<div class="form-group">
										  <div class="input-group">
											<input class="form-control" data-provide="datepicker" value="{% now 'd/m/Y' %}" name="fecha" id="fecha" name="fecha">
											<div class="input-group-addon">
											  <i class="fa fa-calendar"></i>
											</div>
										  </div><!-- /.input group -->
										</div><!-- /.form group -->
									  </div>
									</td>
									<td>
									  <!-- time Picker -->
									  <div style="width: 70%" class="bootstrap-timepicker">
										<div class="form-group">
										  <div class="input-group">
											<input type="text" value="{% now 'h:i A' %}" class="form-control timepicker" name="hora" id="hora" name="hora"/>
											<div class="input-group-addon">
											  <i class="fa fa-clock-o"></i>
											</div>
										  </div><!-- /.input group -->
										</div><!-- /.form group -->
									  </div>
									</td>
									<td>
									  <div>
										<select class="multiple" id="id_listas" name="listas" multiple required>
										  {% for x,y in form.fields.listas.choices %}
											<option value="{{ x }}"{% if form.fields.listas.value == x %} {% endif %}>{{ y }}</option>
										  {% endfor %}
										</select>
									  </div>
									</td>
								  </tr>
								</table>

								<label for="titulomensaje"><h5>Titulo del mensaje:</h5></label>
								<input type="text" style="width: 100%" maxlength="50" class="form-control" required="require" id="titulo_mensaje" placeholder="Titulo del mensaje" name="titulo_mensaje">
								<label for="cuerpomensaje"><h5>Cuerpo del mensaje:</h5></label>
								<textarea style='width: 100%;' class="form-control" required maxlength="1000" rows="4" id='cuerpo_mensaje' value="{{ cuerpo_mensaje }}" name="cuerpo_mensaje"></textarea>
								<input name="enviadopor" value="{{ user.username }}" required type="hidden" id="enviadopor"/>

							</div>

							<div id="file_container">
							  <div class="formset" id="formset" data-formset-prefix="{{ formset.prefix }}">
								<div class="box-header" data-original-title>
								  <h2 class="box-title">Archivos que desea adjuntar:</h2>
								</div>

								  {{ formset.media }}
								  {% load formset_tags %}
								  {{ formset.management_form }}

								  <!-- This button will add a new form when clicked -->
								  <button type="button" class="btn btn-block btn-success btn-lg" data-formset-add>Añadir Archivo(s)</button>

								  <div data-formset-body>
									<!-- New forms will be inserted in here -->
									{% for form in formset %}
										<div data-formset-form>
										  {{ form }}
										  <button id="bottom-right" type="button" class="btn btn-danger" data-formset-delete-button>Eliminar Archivo</button>
										</div>
									{% endfor %}
								  </div>

								  <!-- The empty form template. By wrapping this in a <script> tag, the
								  __prefix__ placeholder can easily be replaced in both attributes and
								  any scripts -->

								  <script type="form-template" data-formset-empty-form>
								  {% escapescript %}
									  <div class="dropzone" id="dropzone" data-formset-form>
										{% for field in formset.empty_form %}
											  {{ field }}
										{% endfor %}
										<button id="bottom-right" type="button" class="btn btn-danger" data-formset-delete-button>Eliminar Archivo</button>
									  </div>
								  {% endescapescript %}
								  </script>

								  <script>
								  jQuery(function($) {
								  $("#formset").formset({
									  'animateForms': true,
									  'reorderMode': 'animate',
									});
								  });

								  </script>

							  </div>
							</div>

						</div>

						<hr>
						<button type="submit" id="submit-all" class="btn btn-block btn-primary btn-lg">Enviar boletín</button>

					</form>

                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
        </section><!-- /.content -->

{% endblock %}